import Database from 'better-sqlite3';
import { v4 as uuidv4 } from 'uuid';

export const seedFestivals = (db: Database.Database) => {
  console.log('Seeding festivals...');

  const festivals = [
    {
      id: uuidv4(),
      name: 'Republic Day Sale',
      platform: 'amazon_india',
      start_date: '2025-01-20',
      end_date: '2025-01-28',
      expected_discount: '20-50%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'TVs']),
      confidence: 0.95,
      historical_avg_discount: 35,
      description: 'Amazon Great Republic Day Sale - Huge discounts on electronics, smartphones, and more',
      banner_url: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=800',
    },
    {
      id: uuidv4(),
      name: 'Republic Day Sale',
      platform: 'flipkart',
      start_date: '2025-01-20',
      end_date: '2025-01-28',
      expected_discount: '20-60%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'TVs']),
      confidence: 0.95,
      historical_avg_discount: 38,
      description: 'Flipkart Republic Day Sale - Best deals on mobiles, laptops, and home appliances',
      banner_url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800',
    },
    {
      id: uuidv4(),
      name: 'Valentine\'s Day Sale',
      platform: 'myntra',
      start_date: '2025-02-10',
      end_date: '2025-02-14',
      expected_discount: '30-70%',
      categories: JSON.stringify(['Wearables', 'Audio']),
      confidence: 0.90,
      historical_avg_discount: 45,
      description: 'Myntra Valentine\'s Special - Perfect gifts for your loved ones',
      banner_url: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800',
    },
    {
      id: uuidv4(),
      name: 'Valentine\'s Day Sale',
      platform: 'ajio',
      start_date: '2025-02-10',
      end_date: '2025-02-14',
      expected_discount: '25-60%',
      categories: JSON.stringify(['Wearables', 'Audio']),
      confidence: 0.88,
      historical_avg_discount: 40,
      description: 'AJIO Love Special - Tech accessories and wearables at great prices',
      banner_url: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
    },
    {
      id: uuidv4(),
      name: 'Holi Dhamaka Sale',
      platform: 'flipkart',
      start_date: '2025-03-20',
      end_date: '2025-03-26',
      expected_discount: '15-45%',
      categories: JSON.stringify(['Smartphones', 'Audio', 'Home']),
      confidence: 0.85,
      historical_avg_discount: 28,
      description: 'Celebrate Holi with colorful deals on electronics',
      banner_url: 'https://images.unsplash.com/photo-1583241800698-821b11c44e5c?w=800',
    },
    {
      id: uuidv4(),
      name: 'Holi Sale',
      platform: 'meesho',
      start_date: '2025-03-20',
      end_date: '2025-03-26',
      expected_discount: '20-50%',
      categories: JSON.stringify(['Audio', 'Wearables', 'Home']),
      confidence: 0.82,
      historical_avg_discount: 32,
      description: 'Meesho Holi Mega Sale - Budget-friendly electronics',
      banner_url: 'https://images.unsplash.com/photo-1616164942740-5078d42d3b98?w=800',
    },
    {
      id: uuidv4(),
      name: 'Summer Sale',
      platform: 'amazon_india',
      start_date: '2025-05-01',
      end_date: '2025-05-15',
      expected_discount: '25-55%',
      categories: JSON.stringify(['Laptops', 'Smartphones', 'Audio', 'Cameras', 'Home']),
      confidence: 0.92,
      historical_avg_discount: 38,
      description: 'Amazon Summer Sale - Beat the heat with hot deals',
      banner_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    },
    {
      id: uuidv4(),
      name: 'Summer Sale',
      platform: 'flipkart',
      start_date: '2025-05-01',
      end_date: '2025-05-15',
      expected_discount: '20-50%',
      categories: JSON.stringify(['Laptops', 'Smartphones', 'Audio', 'TVs', 'Home']),
      confidence: 0.90,
      historical_avg_discount: 35,
      description: 'Flipkart Summer Special Sale',
      banner_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    },
    {
      id: uuidv4(),
      name: 'Summer Fashion Sale',
      platform: 'myntra',
      start_date: '2025-05-01',
      end_date: '2025-05-15',
      expected_discount: '30-60%',
      categories: JSON.stringify(['Wearables', 'Audio']),
      confidence: 0.88,
      historical_avg_discount: 42,
      description: 'Myntra End of Reason Sale - Summer Edition',
      banner_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    },
    {
      id: uuidv4(),
      name: 'Amazon Prime Day',
      platform: 'amazon_india',
      start_date: '2025-07-15',
      end_date: '2025-07-16',
      expected_discount: '30-70%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.98,
      historical_avg_discount: 48,
      description: 'Amazon Prime Day - Exclusive deals for Prime members',
      banner_url: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800',
    },
    {
      id: uuidv4(),
      name: 'Independence Day Sale',
      platform: 'amazon_india',
      start_date: '2025-08-08',
      end_date: '2025-08-16',
      expected_discount: '25-60%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.96,
      historical_avg_discount: 42,
      description: 'Amazon Freedom Sale - Celebrate Independence with great deals',
      banner_url: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=800',
    },
    {
      id: uuidv4(),
      name: 'Independence Day Sale',
      platform: 'flipkart',
      start_date: '2025-08-08',
      end_date: '2025-08-16',
      expected_discount: '25-65%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'TVs', 'Home']),
      confidence: 0.96,
      historical_avg_discount: 44,
      description: 'Flipkart Freedom Sale - Biggest deals of the season',
      banner_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
    },
    {
      id: uuidv4(),
      name: 'Independence Day Sale',
      platform: 'tatacliq',
      start_date: '2025-08-08',
      end_date: '2025-08-16',
      expected_discount: '20-50%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs']),
      confidence: 0.90,
      historical_avg_discount: 35,
      description: 'Tata CLiQ Independence Day Sale',
      banner_url: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
    },
    {
      id: uuidv4(),
      name: 'Onam Sale',
      platform: 'amazon_india',
      start_date: '2025-08-25',
      end_date: '2025-09-05',
      expected_discount: '20-45%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'TVs', 'Home']),
      confidence: 0.88,
      historical_avg_discount: 32,
      description: 'Amazon Onam Special - Traditional festival, modern deals',
      banner_url: 'https://images.unsplash.com/photo-1607083206325-caf1edba7a0f?w=800',
    },
    {
      id: uuidv4(),
      name: 'Onam Sale',
      platform: 'flipkart',
      start_date: '2025-08-25',
      end_date: '2025-09-05',
      expected_discount: '20-50%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'TVs', 'Home']),
      confidence: 0.88,
      historical_avg_discount: 34,
      description: 'Flipkart Onam Special Sale',
      banner_url: 'https://images.unsplash.com/photo-1606220838315-056192d5e927?w=800',
    },
    {
      id: uuidv4(),
      name: 'Navratri & Dussehra Sale',
      platform: 'amazon_india',
      start_date: '2025-10-01',
      end_date: '2025-10-10',
      expected_discount: '25-55%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'TVs', 'Home']),
      confidence: 0.92,
      historical_avg_discount: 38,
      description: 'Amazon Navratri Sale - Festive offers on electronics',
      banner_url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800',
    },
    {
      id: uuidv4(),
      name: 'Navratri & Dussehra Sale',
      platform: 'flipkart',
      start_date: '2025-10-01',
      end_date: '2025-10-10',
      expected_discount: '25-60%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'TVs', 'Home']),
      confidence: 0.92,
      historical_avg_discount: 40,
      description: 'Flipkart Navratri Dhamaka Sale',
      banner_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800',
    },
    {
      id: uuidv4(),
      name: 'Great Indian Festival',
      platform: 'amazon_india',
      start_date: '2025-10-15',
      end_date: '2025-11-05',
      expected_discount: '30-80%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.99,
      historical_avg_discount: 52,
      description: 'Amazon Great Indian Festival - Biggest sale of the year',
      banner_url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800',
    },
    {
      id: uuidv4(),
      name: 'Big Billion Days',
      platform: 'flipkart',
      start_date: '2025-10-15',
      end_date: '2025-11-05',
      expected_discount: '30-85%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.99,
      historical_avg_discount: 55,
      description: 'Flipkart Big Billion Days - India\'s biggest shopping festival',
      banner_url: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800',
    },
    {
      id: uuidv4(),
      name: 'Diwali Sale',
      platform: 'myntra',
      start_date: '2025-10-15',
      end_date: '2025-11-05',
      expected_discount: '40-80%',
      categories: JSON.stringify(['Wearables', 'Audio']),
      confidence: 0.95,
      historical_avg_discount: 58,
      description: 'Myntra Diwali Sale - Light up your life with amazing deals',
      banner_url: 'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=800',
    },
    {
      id: uuidv4(),
      name: 'Diwali Bonanza',
      platform: 'tatacliq',
      start_date: '2025-10-15',
      end_date: '2025-11-05',
      expected_discount: '25-65%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.94,
      historical_avg_discount: 42,
      description: 'Tata CLiQ Diwali Bonanza',
      banner_url: 'https://images.unsplash.com/photo-1607082350899-7e105aa886ae?w=800',
    },
    {
      id: uuidv4(),
      name: 'Diwali Dhamaka',
      platform: 'jiomart',
      start_date: '2025-10-15',
      end_date: '2025-11-05',
      expected_discount: '25-60%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'TVs', 'Home']),
      confidence: 0.92,
      historical_avg_discount: 40,
      description: 'JioMart Diwali Dhamaka - Digital India Sale',
      banner_url: 'https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?w=800',
    },
    {
      id: uuidv4(),
      name: 'Black Friday Sale',
      platform: 'amazon_india',
      start_date: '2025-11-24',
      end_date: '2025-11-30',
      expected_discount: '30-75%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.96,
      historical_avg_discount: 48,
      description: 'Amazon Black Friday Sale - Global shopping extravaganza',
      banner_url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800',
    },
    {
      id: uuidv4(),
      name: 'Black Friday Sale',
      platform: 'flipkart',
      start_date: '2025-11-24',
      end_date: '2025-11-30',
      expected_discount: '30-70%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.94,
      historical_avg_discount: 46,
      description: 'Flipkart Black Friday Sale',
      banner_url: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800',
    },
    {
      id: uuidv4(),
      name: 'Black Friday Sale',
      platform: 'tatacliq',
      start_date: '2025-11-24',
      end_date: '2025-11-30',
      expected_discount: '25-60%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs']),
      confidence: 0.90,
      historical_avg_discount: 40,
      description: 'Tata CLiQ Black Friday Deals',
      banner_url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800',
    },
    {
      id: uuidv4(),
      name: 'Year End Sale',
      platform: 'amazon_india',
      start_date: '2025-12-20',
      end_date: '2026-01-02',
      expected_discount: '25-65%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.94,
      historical_avg_discount: 42,
      description: 'Amazon Year End Sale - Ring in the new year with great deals',
      banner_url: 'https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=800',
    },
    {
      id: uuidv4(),
      name: 'Year End Sale',
      platform: 'flipkart',
      start_date: '2025-12-20',
      end_date: '2026-01-02',
      expected_discount: '25-70%',
      categories: JSON.stringify(['Smartphones', 'Laptops', 'Audio', 'Wearables', 'Cameras', 'TVs', 'Home']),
      confidence: 0.94,
      historical_avg_discount: 44,
      description: 'Flipkart Year End Sale - New year, new deals',
      banner_url: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
    },
    {
      id: uuidv4(),
      name: 'Budget Phone Days',
      platform: 'flipkart',
      start_date: '2025-01-15',
      end_date: '2025-01-17',
      expected_discount: '20-40%',
      categories: JSON.stringify(['Smartphones']),
      confidence: 0.85,
      historical_avg_discount: 28,
      description: 'Flipkart Budget Phone Days - Monthly smartphone sale',
      banner_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
    },
  ];

  const insert = db.prepare(`
    INSERT INTO festivals (
      id, name, platform, start_date, end_date, expected_discount,
      categories, confidence, historical_avg_discount, description, banner_url
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const insertMany = db.transaction((festivals) => {
    for (const festival of festivals) {
      insert.run(
        festival.id,
        festival.name,
        festival.platform,
        festival.start_date,
        festival.end_date,
        festival.expected_discount,
        festival.categories,
        festival.confidence,
        festival.historical_avg_discount,
        festival.description,
        festival.banner_url
      );
    }
  });

  insertMany(festivals);

  console.log(`✓ Seeded ${festivals.length} festivals`);
  return festivals;
};
